/*
 * main.c
 *
 * ECEC 661/402 - Quiz 2 (real) - Add Constant -1 IP test app
 *
 * Bare-metal Vitis test application for the custom "add_const_axi" AXI4-Lite
 * IP, which wraps the IP-Catalog Adder/Subtractor (xilinx.com:ip:c_addsub:12.0)
 * configured with B held to a constant -1 (signed 32-bit, all ones, latency 0,
 * no CE).  The user logic therefore computes:
 *
 *     z = x + (-1) = x - 1     (signed 32-bit)
 *
 * Register map (byte offsets from XPAR_ADD_CONST_AXI_0_S00_AXI_BASEADDR):
 *
 *     0x00  X_IN   R/W  signed 32-bit input
 *     0x04  Z_OUT  R    signed 32-bit result, z = x - 1
 *     0x08         R/W  reserved (returns 0)
 *     0x0C         R/W  reserved (returns 0)
 *
 * Because the IP is combinational, software writes X_IN and immediately reads
 * Z_OUT - no "valid" / "done" handshake is needed.
 *
 * Note: per the quiz hand-out, the test-app result is NOT part of the quiz
 * deliverable.  This file is provided as the matching software companion so
 * the design can be exercised over UART after `xsa/add_const.xsa` is loaded
 * into Vitis on the Cora Z7-07S.
 */

#include <stdio.h>
#include "xparameters.h"
#include "xil_io.h"
#include "xil_printf.h"
#include "xil_types.h"
#include "sleep.h"

/* --------------------------------------------------------------------------
 * Base address.  Vitis emits XPAR_ADD_CONST_AXI_0_S00_AXI_BASEADDR after the
 * platform is built from the XSA.  Fall back to 0x43C00000 (the address we
 * assign in scripts/create_bd.tcl) if the platform hasn't been built yet so
 * this file still compiles standalone.
 * --------------------------------------------------------------------------
 */
#ifdef XPAR_ADD_CONST_AXI_0_S00_AXI_BASEADDR
#define AC_BASE             XPAR_ADD_CONST_AXI_0_S00_AXI_BASEADDR
#else
#warning "XPAR_ADD_CONST_AXI_0_S00_AXI_BASEADDR not found - using default 0x43C00000"
#define AC_BASE             0x43C00000U
#endif

#define AC_X_IN_OFFSET      0x00U
#define AC_Z_OUT_OFFSET     0x04U

/* --------------------------------------------------------------------------
 * Register-level helpers.  Mirror the Xilinx "mWriteReg"/"mReadReg" naming
 * pattern that ships with the autogenerated driver template.
 * --------------------------------------------------------------------------
 */
#define ADD_CONST_mWriteReg(base, ofst, val) \
    Xil_Out32((u32)(base) + (u32)(ofst), (u32)(val))
#define ADD_CONST_mReadReg(base, ofst) \
    Xil_In32((u32)(base) + (u32)(ofst))

static inline void ac_write_x(s32 x)
{
    ADD_CONST_mWriteReg(AC_BASE, AC_X_IN_OFFSET, (u32) x);
}

static inline s32 ac_read_z(void)
{
    return (s32) ADD_CONST_mReadReg(AC_BASE, AC_Z_OUT_OFFSET);
}

/* --------------------------------------------------------------------------
 * Pretty-printing helpers
 *
 * The output is intentionally framed in box-drawing ASCII so a PuTTY capture
 * for the report reads cleanly with no extra editing:
 *
 *   +===========================================================+
 *   |                       banner                              |
 *   +===========================================================+
 *
 *   +-----+--------------+------------+--------------+------------+--------+
 *   |  #  |    x (dec)   |  x (hex)   |    z (dec)   |  z (hex)   | check  |
 *   +-----+--------------+------------+--------------+------------+--------+
 *   |  0  |          -5  | 0xFFFFFFFB |          -6  | 0xFFFFFFFA |  [OK]  |
 *   ...
 *
 * All column widths live in COL_* so the rule and row formats stay in sync.
 * --------------------------------------------------------------------------
 */
#define COL_IDX  3
#define COL_DEC  12
#define COL_HEX  10
#define COL_CHK  6

#define BOX_WIDTH  64

static void print_banner_top(void)
{
    xil_printf("\r\n+");
    for (int i = 0; i < BOX_WIDTH - 2; i++) {
        xil_printf("=");
    }
    xil_printf("+\r\n");
}

static void print_banner_line(const char *text)
{
    int textlen = 0;
    while (text[textlen] != '\0') {
        textlen++;
    }
    int inner = BOX_WIDTH - 2;
    int padl  = (inner - textlen) / 2;
    int padr  = inner - textlen - padl;
    if (padl < 0) {
        padl = 0;
    }
    if (padr < 0) {
        padr = 0;
    }

    xil_printf("|");
    for (int i = 0; i < padl; i++) {
        xil_printf(" ");
    }
    xil_printf("%s", text);
    for (int i = 0; i < padr; i++) {
        xil_printf(" ");
    }
    xil_printf("|\r\n");
}

static void print_table_rule(void)
{
    /* Matches the row format below: "+-----+--------------+------------+
     * --------------+------------+--------+" with col widths COL_*.      */
    xil_printf("+");
    for (int i = 0; i < COL_IDX + 2; i++) {
        xil_printf("-");
    }
    xil_printf("+");
    for (int i = 0; i < COL_DEC + 2; i++) {
        xil_printf("-");
    }
    xil_printf("+");
    for (int i = 0; i < COL_HEX + 2; i++) {
        xil_printf("-");
    }
    xil_printf("+");
    for (int i = 0; i < COL_DEC + 2; i++) {
        xil_printf("-");
    }
    xil_printf("+");
    for (int i = 0; i < COL_HEX + 2; i++) {
        xil_printf("-");
    }
    xil_printf("+");
    for (int i = 0; i < COL_CHK + 2; i++) {
        xil_printf("-");
    }
    xil_printf("+\r\n");
}

static void print_table_header(void)
{
    char line[160];

    print_table_rule();
    (void) snprintf(line, sizeof line,
                    "| %-*s | %-*s | %-*s | %-*s | %-*s | %-*s |\r\n",
                    COL_IDX, " # ",
                    COL_DEC, "  x (dec)",
                    COL_HEX, " x (hex)",
                    COL_DEC, "  z (dec)",
                    COL_HEX, " z (hex)",
                    COL_CHK, "check");
    xil_printf("%s", line);
    print_table_rule();
}

static void print_table_row(int idx, s32 x_in, s32 z_out, int ok)
{
    char line[160];
    /* xil_printf supports %d/%x but no width/0-pad combos for u32 reliably,
     * so format columns as strings via snprintf first and then emit them.   */
    char dx[32];
    char hx[32];
    char dz[32];
    char hz[32];
    char chk[8];

    (void) snprintf(dx,  sizeof dx,  "%d",  (int) x_in);
    (void) snprintf(hx,  sizeof hx,  "0x%08X", (unsigned int) x_in);
    (void) snprintf(dz,  sizeof dz,  "%d",  (int) z_out);
    (void) snprintf(hz,  sizeof hz,  "0x%08X", (unsigned int) z_out);
    (void) snprintf(chk, sizeof chk, "%s",   ok ? "[OK]" : "[FAIL]");

    (void) snprintf(line, sizeof line,
                    "| %*d | %*s | %*s | %*s | %*s | %*s |\r\n",
                    COL_IDX, idx,
                    COL_DEC, dx,
                    COL_HEX, hx,
                    COL_DEC, dz,
                    COL_HEX, hz,
                    COL_CHK, chk);
    xil_printf("%s", line);
}

/* --------------------------------------------------------------------------
 * Test vectors
 *
 * Reference run from the quiz hand-out (printed PuTTY screen):
 *     x = -5 .. 3   ->  z = x - 1
 *
 * Plus a few signed boundary checks so the report shows the IP behaves
 * correctly across the full 32-bit signed range, including the wrap from
 * INT32_MIN.  All expected values are computed on the host so a silent
 * IP-config drift cannot hide a bug.
 * --------------------------------------------------------------------------
 */
/* Avoid the well-known "0x80000000 is unsigned long" / "-2147483648 is two
 * tokens in C" portability traps; build the boundary values from arithmetic
 * the preprocessor cannot misread. */
#define INT32_MAX_S32  ((s32) 0x7FFFFFFF)
#define INT32_MIN_S32  ((s32) (-INT32_MAX_S32 - 1))

static const s32 test_vector[] = {
    -5, -4, -3, -2, -1, 0, 1, 2, 3,
    100,
    -1000,
    INT32_MAX_S32,            /*  2147483647   ->  2147483646                */
    INT32_MIN_S32,            /* -2147483648   ->  2147483647 (signed wrap)  */
};

#define N_TESTS  ((int)(sizeof test_vector / sizeof test_vector[0]))

/* --------------------------------------------------------------------------
 * AXI smoke test.
 *
 * Writes a known marker to X_IN, reads it back, then reads Z_OUT and verifies
 * it equals (marker - 1).  If any of these hang or mismatch the IP / block
 * design / bitstream is broken before the main vector loop ever starts, and
 * the loop would otherwise just hang silently after printing the table
 * header.  Returning 0 means the bus is alive; -1 means we should give up.
 * --------------------------------------------------------------------------
 */
static int axi_probe(void)
{
    static const u32 marker = 0xA5A5A5A5U;

    xil_printf("  Probing IP at 0x%08X ...\r\n", (unsigned int) AC_BASE);

    ac_write_x((s32) marker);
    u32 rb_x = (u32) ADD_CONST_mReadReg(AC_BASE, AC_X_IN_OFFSET);
    u32 rb_z = (u32) ADD_CONST_mReadReg(AC_BASE, AC_Z_OUT_OFFSET);
    u32 expected_z = marker - 1U;

    int x_ok = (rb_x == marker);
    int z_ok = (rb_z == expected_z);

    xil_printf("    X_IN  write/read : 0x%08X -> 0x%08X  %s\r\n",
               (unsigned int) marker, (unsigned int) rb_x,
               x_ok ? "[OK]" : "[FAIL]");
    xil_printf("    Z_OUT  readback  : 0x%08X (expect 0x%08X)  %s\r\n",
               (unsigned int) rb_z, (unsigned int) expected_z,
               z_ok ? "[OK]" : "[FAIL]");

    if (!x_ok || !z_ok) {
        xil_printf("\r\n");
        xil_printf("  *** AXI probe FAILED ***\r\n");
        xil_printf("  Check that the bitstream is programmed and that the\r\n");
        xil_printf("  block design wires PS M_AXI_GP0 -> add_const_axi_0/s00_axi\r\n");
        xil_printf("  with FCLK_CLK0 / proc_sys_reset_0/peripheral_aresetn,\r\n");
        xil_printf("  and that XPAR_ADD_CONST_AXI_0_S00_AXI_BASEADDR matches\r\n");
        xil_printf("  the address used in the Address Editor.\r\n");
        return -1;
    }

    xil_printf("    Probe OK\r\n\r\n");
    return 0;
}

int main(void)
{
    /* Startup window so the serial monitor has time to attach.              */
    for (int i = 3; i > 0; i--) {
        xil_printf("add_const starting in %d...\r\n", i);
        sleep(1);
    }

    print_banner_top();
    print_banner_line("ECEC 661 / 402  Quiz 2");
    print_banner_line("Add Constant -1   AXI4-Lite Custom IP");
    print_banner_line("");
    {
        char line[80];
        (void) snprintf(line, sizeof line,
                        "IP base address : 0x%08X",
                        (unsigned int) AC_BASE);
        print_banner_line(line);
    }
    print_banner_top();
    xil_printf("\r\n");

    xil_printf("  Register map\r\n");
    xil_printf("  ------------\r\n");
    xil_printf("    0x00  X_IN   R/W   32-bit signed input\r\n");
    xil_printf("    0x04  Z_OUT  R     z = x + (-1) = x - 1\r\n");
    xil_printf("\r\n");

    /* Bring up the bus first so a hang is obvious instead of silent.        */
    if (axi_probe() != 0) {
        while (1) {
            /* park forever; the FAIL banner is already on the console */
        }
    }

    xil_printf("  IP test vectors  (z expected = x - 1)\r\n");
    print_table_header();

    unsigned pass = 0;
    unsigned fail = 0;

    for (int i = 0; i < N_TESTS; i++) {
        s32 x_in     = test_vector[i];
        s32 expected = (s32) ((u32) x_in - 1U);   /* mod-2^32 like the IP    */

        ac_write_x(x_in);
        s32 z_out = ac_read_z();

        int ok = (z_out == expected);

        print_table_row(i, x_in, z_out, ok);

        if (!ok) {
            xil_printf("        ERROR: expected z = %d  (0x%08X)\r\n",
                       (int) expected, (unsigned int) expected);
            fail++;
        } else {
            pass++;
        }
    }

    print_table_rule();

    xil_printf("\r\n");
    print_banner_top();
    {
        char line[80];
        (void) snprintf(line, sizeof line,
                        "Summary : %u / %d PASSED  (%u failed)",
                        pass, N_TESTS, fail);
        print_banner_line(line);
        if (fail == 0U) {
            print_banner_line("RESULT  : add_const_axi behaves correctly");
        } else {
            print_banner_line("RESULT  : *** mismatch detected ***");
        }
    }
    print_banner_top();
    xil_printf("\r\n");

    while (1) {
        /* Idle forever so the JTAG/UART session stays open for the screen-
         * shot in the report.                                                */
    }

    return 0;
}
